# Generated by Django 5.2.1 on 2025-06-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='business_trip_end',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание командировки'),
        ),
        migrations.AddField(
            model_name='employee',
            name='business_trip_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало командировки'),
        ),
        migrations.AddField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Рабочая почта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
