# Generated by Django 5.2.1 on 2025-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_business_trip_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='business_trip_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город командировки'),
        ),
        migrations.AddField(
            model_name='employee',
            name='business_trip_region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регион командировки'),
        ),
        migrations.AddField(
            model_name='employee',
            name='business_trip_task',
            field=models.TextField(blank=True, verbose_name='Задание на командировку'),
        ),
    ]
