# Generated by Django 5.2.1 on 2025-06-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTripApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('destination', models.CharField(max_length=255, verbose_name='Куда будет командировка')),
                ('purpose', models.TextField(verbose_name='Цель командировки')),
                ('funding', models.TextField(blank=True, verbose_name='Финансирование')),
                ('start_date', models.DateField(verbose_name='Дата начала командировки')),
                ('end_date', models.DateField(verbose_name='Дата окончания командировки')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Заявка на командировку',
                'verbose_name_plural': 'Заявки на командировку',
                'ordering': ['-application_date'],
            },
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
